################################################################################
# Sensors
################################################################################
sensor:
  # Rack Room Temperature
  - platform: dallas_temp
    address: 0x1b15ffd446022c28
    name: Room Temperature
    id: ${device_internal_name}_room_temperature
    force_update: true
    update_interval: 30s
    resolution: 11
    accuracy_decimals: 2

  # Rack Inside Temperature
  - platform: dallas_temp
    address: 0x5f17efd446a19e28
    name: Inside Temperature
    id: ${device_internal_name}_inside_temperature
    force_update: true
    update_interval: 30s
    resolution: 11
    accuracy_decimals: 2

